calcul_kcal/urls.py
from django.urls import path
from .views import (
    home_view, calculation_view
)

app_name = "calcul_kcal"

urlpatterns = [
    path("home/", home_view, name="home"),
    path("calculation_view/", calculation_view, name="calculation_view"),
]

off_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include
from .views import home_screen_view, mention_legal_view
from account.views import (
    registration_view, logout_view, login_view, account_view)


urlpatterns = [
    path("", home_screen_view, name="home"),
    path("legal", mention_legal_view, name="legal"),
    path("admin/", admin.site.urls),
    path("register/", registration_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("login/", login_view, name="login"),
    path("account/", account_view, name="account"),
    path("substitute/", include("substitute.urls")),
    path("calcul_kcal/", include("calcul_kcal.urls")),



    path("reset_password/", auth_views.PasswordResetView.as_view(
        template_name="account/password_reset.html"),
        name="reset_password"),

    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(
        template_name="account/password_reset_sent.html"),
        name="password_reset_done"),

    path("reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(
             template_name="account/password_reset_form.html"),
         name="password_reset_confirm"),

    path("reset_password_complete/",
         auth_views.PasswordResetCompleteView.as_view(
             template_name="account/password_reset_done.html"),
         name="password_reset_complete"),

]

calcul_kcal/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse


def home_view(request):
    """ calculette page"""
    user = request.user
    if not user.is_authenticated:
        return redirect("home")
    context = {}

    return render(request, "calcul_kcal/kcal_home.html", context)


def calculation_view(request):
    """ calcul in ajax IMC + metabolisme an return them"""
    sexe = request.POST.get("sexe")
    activite = request.POST.get("activite")
    age = request.POST.get("age")
    taille = request.POST.get("taille")
    poids = request.POST.get("poids")
    context = {}

    try:
        if age != "" and taille != "" and poids != "":
            # metabolisme
            calcul_metabolisme = ((float(sexe) * (float(poids) ** 0.48)
                                  * (float(taille) ** 0.5)
                                  * (float(age) ** -0.13))
                                  * (1000 / 4.1855)
                                  * float(activite))
            somme = round(calcul_metabolisme, 2)
            matabolisme = "- Votre consommation est de " + \
                str(somme) + " Kcal/jour"
            context["operation_metabolisme"] = matabolisme

            # imc
            imc = float(poids) / (float(taille) ** 2)
            if imc < 18.5:
                corpulence = "Insuffisance pondérale (<18.5)"
            elif imc >= 18.5 and imc <= 25:
                corpulence = "Corpulence normale (18.5-25)"
            elif imc > 25 and imc <= 30:
                corpulence = "Surpoids (25-30)"
            elif imc > 30 and imc <= 35:
                corpulence = "Obésité modérée (30-35)"
            elif imc > 35 and imc <= 40:
                corpulence = "Obésité sévère (35-40)"
            else:
                corpulence = "Obésité morbide ou massive (>40)"

            somme = round(imc, 2)
            context["operation_imc"] = "- Votre IMC est de : " + \
                str(somme) + " votre corpulence est : " + corpulence
        else:
            error = "ooops vous avez oublié une valeur :/"
            context["error"] = error
    except ValueError:
        error = "Il faut mettre des nombres ;)"
        context["error"] = error

    return JsonResponse(context)

calcul_kcal/templates/calcul_kcal/base.html
{% extends 'base.html' %} {% block content %}

<section class="page-section bg-primary" id="about">
  <div class="container">
      {% block substitute-content %}{% endblock substitute-content %}

  </div>
</section>
{% endblock content %}

calcul_kcal/templates/calcul_kcal/kcal_home.html
{% extends 'calcul_kcal/base.html' %} {% block substitute-content %}
<div class="row">
  <div class="col">
    <h1
      class="
        text-white
        font-weight-light
        mb-5
        justify-content-center
        text-center
      "
    >
      Calculatrice : IMC + métabolisme
    </h1>
    Pour faire les calculs, veillez remplir les elements suivants :
  </div>
</div>

<div class="row">
  <div class="col">
    <form method="POST">
      {% csrf_token %}

      <div>
        <input
          type="radio"
          id="homme"
          name="sexe"
          value="1.083"
          step="0.001"
          checked
          required
        />
        <label for="homme"><i class="fa fa-mars fa-2x"></i></label>

        <input
          type="radio"
          id="femme"
          name="sexe"
          value="0.963"
          required
          step="0.001"
        />
        <label for="femme"><i class="fa fa-venus fa-2x"></i></label>
      </div>

      <div>
        <input
          type="radio"
          id="sédentaire"
          name="activite"
          value="1.37"
          checked
          required
        />
        <label for="sédentaire">sédentaire</label>

        <input type="radio" id="actif" name="activite" value="1.55" required />
        <label for="actif">actif</label>

        <input
          type="radio"
          id="sportif"
          name="activite"
          value="1.80"
          required
        />
        <label for="sportif">sportif</label>
      </div>

      <div>
        <label for="age">Age</label>
        <input type="number" name="age" id="age" placeholder="30" required />
      </div>
      <div>
        <label for="taille">Taille (m)</label>
        <input
          type="number"
          name="taille"
          id="taille"
          placeholder="1.75"
          step="0.01"
          required
        />
      </div>
      <div>
        <label for="poids">Poids (kg)</label>
        <input
          type="number"
          name="poids"
          id="poids"
          placeholder="65"
          step="0.1"
          required
        />
      </div>

      <input
        class="btn btn-light"
        id="fetch-call"
        type="submit"
        value="Calculer"
      />
    </form>
  </div>
</div>

<div
  class="text-white font-weight-light mb-5 justify-content-center text-center"
>
  <div>Votre resultat :</div>
  <div id="operation_imc"></div>
  <div id="operation_metabolisme"></div>
  <div id="error"></div>
</div>

<script>
  document.querySelector("#fetch-call").addEventListener("click", (event) => {
    event.preventDefault();

    let form = new FormData();

    form.append("sexe", document.querySelector('[name="sexe"]:checked').value);
    form.append(
      "activite",
      document.querySelector('[name="activite"]:checked').value
    );
    form.append("age", document.querySelector("#age").value);
    form.append("taille", document.querySelector("#taille").value);
    form.append("poids", document.querySelector("#poids").value);

    let csrfTokenValue = document.querySelector(
      "[name=csrfmiddlewaretoken]"
    ).value;
    let request = new Request("{% url 'calcul_kcal:calculation_view' %}", {
      method: "POST",
      body: form,
      headers: { "X-CSRFToken": csrfTokenValue },
    });
    fetch(request)
      .then((response) => response.json())
      .then((result) => {
        console.log(result);
        if (result["error"]) {
          // Hide result
          document.querySelector("#operation_metabolisme").style.display =
            "none";
          document.querySelector("#operation_imc").style.display = "none";

          // show error
          let resultParagraph_error = document.querySelector("#error");
          resultParagraph_error.style.display = "block";

          resultParagraph_error.innerHTML = result["error"];
        } else {
          // hide error
          document.querySelector("#error").style.display = "none";

          // show result
          document.querySelector("#operation_metabolisme").style.display =
            "block";
          document.querySelector("#operation_imc").style.display = "block";

          let resultParagraph_metabolisme = document.querySelector(
            "#operation_metabolisme"
          );

          resultParagraph_metabolisme.innerHTML =
            result["operation_metabolisme"];
          let resultParagraph_imc = document.querySelector("#operation_imc");
          resultParagraph_imc.innerHTML = result["operation_imc"];
        }
      });
  });
</script>

{% endblock substitute-content %}