off_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include
from .views import home_screen_view, mention_legal_view
from account.views import (
    registration_view, logout_view, login_view, account_view)


urlpatterns = [
    path("", home_screen_view, name="home"),
    path("legal", mention_legal_view, name="legal"),
    path("admin/", admin.site.urls),
    path("register/", registration_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("login/", login_view, name="login"),
    path("account/", account_view, name="account"),
    path("substitute/", include("substitute.urls")),
    path("calcul_kcal/", include("calcul_kcal.urls")),



    path("reset_password/", auth_views.PasswordResetView.as_view(
        template_name="account/password_reset.html"),
        name="reset_password"),

    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(
        template_name="account/password_reset_sent.html"),
        name="password_reset_done"),

    path("reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(
             template_name="account/password_reset_form.html"),
         name="password_reset_confirm"),

    path("reset_password_complete/",
         auth_views.PasswordResetCompleteView.as_view(
             template_name="account/password_reset_done.html"),
         name="password_reset_complete"),

]

substitute/urls.py
from django.urls import path
from .views import (
    substitute_views,
    my_food_view,
    add_fav_view,
    rmv_fav_view,
    check_query_views,
)

app_name = "substitute"  # pour appeler la page en front

urlpatterns = [
    path("sub/<str:query>/", substitute_views, name="substitute"),
    path("my_food", my_food_view, name="my_food"),
    path("check_query", check_query_views, name="check_query"),
    path("add_fav", add_fav_view, name="add_fav"),
    path("rmv_fav", rmv_fav_view, name="rmv_fav"),
]

substitute/models.py
from django.db import models
from django.conf import settings


class Nutriscore(models.Model):
    name = models.CharField(max_length=1, unique=True, null=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True, null=False)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    store = models.CharField(null=False, max_length=255)
    url = models.URLField(null=False)
    image_url = models.URLField(null=False)
    product_nutriscore = models.ForeignKey(
        Nutriscore, on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["product_nutriscore", "name"]


class Tag(models.Model):
    name = models.CharField(max_length=200)
    products = models.ManyToManyField(
        "Product", related_name="tags", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

substitute/views.py
from .class_substitute import SubstituteViews
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Product


def check_query_views(request):

    if request.method == "POST":
        if not request.POST.get("query"):
            return redirect("home")
        else:

            query = request.POST.get("query")
            return redirect("substitute:substitute", query=query)
    else:
        return redirect("home")


def substitute_views(request, query):
    object_substitute = SubstituteViews()
    return object_substitute.run_substitute(request, query)


def my_food_view(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("home")
    context = {}

    favorite = Product.objects.filter(users__id=user.id)
    if len(favorite) > 0:

        context["favorites"] = favorite

    return render(request, "substitute/my_food.html", context)


def add_fav_view(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("home")
    fav = request.POST.get("fav")

    prod = Product.objects.get(id=fav)

    prod.users.add(user)

    return JsonResponse({"operation_result": prod.name})


def rmv_fav_view(request):
    user = request.user
    if not user.is_authenticated:
        return redirect("home")
    fav = request.POST.get("fav")

    prod = Product.objects.get(id=fav)
    prod.users.remove(user)

    return JsonResponse({"operation_result": prod.name})

substitute/templates/substitute/base.html
{% extends 'base.html' %} {% block content %}

<section class="page-section bg-primary" id="about">
  <div class="container-fluid">
    <div class="row">
      {% block substitute-content %}{% endblock substitute-content %}
    </div>
  </div>
</section>
{% endblock content %}

substitute/templates/substitute/my_food.html
{% extends 'substitute/base.html' %}{% load static %}
<div></div>

{% block substitute-content %} {% for favorite in favorites %}
<div class="col-md-4 p-5 text-white font-weight-bold text-center">
  <div class="row justify-content-center">
    <a href="{{favorite.url}}"
      ><img
        class="img-fluid rounded"
        src="{{favorite.image_url}}"
        alt="{{favorite.name}}"
        style="width: 10rem; height: 10rem"
    /></a>
  </div>

  <div>
    {{favorite.name}}<button
      class="fav btn btn-primary"
      value="{{favorite.id}}"
    >
      <i class="fas fa-heart-broken"></i>
    </button>
  </div>

  <div class="row justify-content-center">
    {% if favorite.product_nutriscore.name == "a" %}
    <img
      src="{% static 'assets/img/nutriscore-a.svg' %}"
      width="150"
      height="50"
    />
    {% elif favorite.product_nutriscore.name == "b" %}
    <img
      src="{% static 'assets/img/nutriscore-b.svg' %}"
      width="150"
      height="50"
    />
    {% elif favorite.product_nutriscore.name == "c" %}
    <img
      src="{% static 'assets/img/nutriscore-c.svg' %}"
      width="150"
      height="50"
    />
    {% elif favorite.product_nutriscore.name == "d" %}
    <img
      src="{% static 'assets/img/nutriscore-d.svg' %}"
      width="150"
      height="50"
    />
    {% elif favorite.product_nutriscore.name == "e" %}
    <img
      src="{% static 'assets/img/nutriscore-e.svg' %}"
      width="150"
      height="50"
    />
    {% endif %}
  </div>
  <div class="row-12 justify-content-center">Magasin: {{favorite.store}}</div>

  <div></div>
</div>
{% endfor %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
  $(".fav").click(function () {
    event.preventDefault();

    alert("produit supprimé");
    let form = new FormData();

    form.append("fav", $(this).val());
    let csrfTokenValue = document.querySelector(
      "[name=csrfmiddlewaretoken]"
    ).value;
    let request = new Request("{% url 'substitute:rmv_fav' %}", {
      method: "POST",
      body: form,
      headers: { "X-CSRFToken": csrfTokenValue },
    });
    fetch(request)
      .then((response) => response.json())
      .then((result) => {
        let resultParagraph = document.querySelector("#operation");
        resultParagraph.innerHTML = result["operation_result"];
      });
  });

  document
    .querySelector("#fetch-call")
    .addEventListener("click", (event) => {});
</script>
{% endblock substitute-content %}

substitute/templates/substitute/substitute.html
{% extends 'substitute/base.html' %}{% load static %}
<div></div>
{% block substitute-content %} {% if not error %}
<div></div>

{% for substitute in substitutes%}
<div class="col-md-4 p-5 text-white font-weight-bold text-center">
  <div></div>

  <div class="row justify-content-center">
    <a href="{{substitute.url}}"
      ><img
        class="img-fluid rounded"
        src="{{substitute.image_url}}"
        alt="{{substitute.name}}"
        style="width: 10rem; height: 10rem"
    /></a>
  </div>

  <div>
    {{substitute.name}} {% if request.user.is_authenticated %}<button
      class="fav btn btn-primary"
      value="{{substitute.id}}"
    >
      <i class="fas fa-heart"></i>
    </button>

    {% endif %}
  </div>
  <div class="row justify-content-center">
    {% if substitute.product_nutriscore.name == "a" %}
    <img
      src="{% static 'assets/img/nutriscore-a.svg' %}"
      width="150"
      height="50"
    />
    {% elif substitute.product_nutriscore.name == "b" %}
    <img
      src="{% static 'assets/img/nutriscore-b.svg' %}"
      width="150"
      height="50"
    />
    {% elif substitute.product_nutriscore.name == "c" %}
    <img
      src="{% static 'assets/img/nutriscore-c.svg' %}"
      width="150"
      height="50"
    />
    {% elif substitute.product_nutriscore.name == "d" %}
    <img
      src="{% static 'assets/img/nutriscore-d.svg' %}"
      width="150"
      height="50"
    />
    {% elif substitute.product_nutriscore.name == "e" %}
    <img
      src="{% static 'assets/img/nutriscore-e.svg' %}"
      width="150"
      height="50"
    />
    {% endif %}
  </div>
  <div class="row-12 justify-content-center">Magasin: {{substitute.store}}</div>
</div>
{% endfor %} {% else %}
<p>{{error}}</p>

{% endif %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
  $(".fav").click(function () {
    event.preventDefault();

    alert("produit ajouté");
    let form = new FormData();

    form.append("fav", $(this).val());
    let csrfTokenValue = document.querySelector(
      "[name=csrfmiddlewaretoken]"
    ).value;
    let request = new Request("{% url 'substitute:add_fav' %}", {
      method: "POST",
      body: form,
      headers: { "X-CSRFToken": csrfTokenValue },
    });
    fetch(request)
      .then((response) => response.json())
      .then((result) => {
        let resultParagraph = document.querySelector("#operation");
        resultParagraph.innerHTML = result["operation_result"];
      });
  });

  document
    .querySelector("#fetch-call")
    .addEventListener("click", (event) => {});
</script>

{% endblock substitute-content %}