calcul_kcal/urls.py
from django.urls import path
from .views import (
    home_view, calculation_view
)

app_name = "calcul_kcal"

urlpatterns = [
    path("home/", home_view, name="home"),
    path("calculation_view/", calculation_view, name="calculation_view"),
]

off_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include
from .views import home_screen_view, mention_legal_view
from account.views import (
    registration_view, logout_view, login_view, account_view)


urlpatterns = [
    path("", home_screen_view, name="home"),
    path("legal", mention_legal_view, name="legal"),
    path("admin/", admin.site.urls),
    path("register/", registration_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("login/", login_view, name="login"),
    path("account/", account_view, name="account"),
    path("substitute/", include("substitute.urls")),
    path("calcul_kcal/", include("calcul_kcal.urls")),



    path("reset_password/", auth_views.PasswordResetView.as_view(
        template_name="account/password_reset.html"),
        name="reset_password"),

    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(
        template_name="account/password_reset_sent.html"),
        name="password_reset_done"),

    path("reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(
             template_name="account/password_reset_form.html"),
         name="password_reset_confirm"),

    path("reset_password_complete/",
         auth_views.PasswordResetCompleteView.as_view(
             template_name="account/password_reset_done.html"),
         name="password_reset_complete"),

]

substitute/urls.py
from django.urls import path
from .views import (
    substitute_views,
    my_food_view,
    add_fav_view,
    rmv_fav_view,
    check_query_views,
)

app_name = "substitute"  # pour appeler la page en front

urlpatterns = [
    path("sub/<str:query>/", substitute_views, name="substitute"),
    path("my_food", my_food_view, name="my_food"),
    path("check_query", check_query_views, name="check_query"),
    path("add_fav", add_fav_view, name="add_fav"),
    path("rmv_fav", rmv_fav_view, name="rmv_fav"),
]

templates/snippets/contact.html
<section class="page-section" id="contact">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Contactez-nous !</h2>
        <hr class="divider my-4" />
        <p class="text-muted mb-5">Une question ? On est là ;)</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
        <div>+1 (555) 123-4567</div>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
        <a class="d-block" href="mailto:contact@purbeurre.com"
          >contact@purbeurre.com</a
        >
      </div>
    </div>
  </div>
</section>

templates/snippets/footer.html
{% load static %}
<footer class="bg-light py-5">
  <div class="container">
    <div class="small text-center text-muted">
      <a href="{% url 'legal'%}">Mentions Légales</a>
      <!-- This script automatically adds the current year to your website footer-->
      <!-- (credit: https://updateyourfooter.com/)-->
      Copyright &copy; Copyright &copy;
      <a href="#contact">Contact</a>
      <script>
        document.write(new Date().getFullYear());
      </script>
      - Pur Beurre
    </div>
  </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>

templates/snippets/head.html
{% load static %}
<head>
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Pur Beurre</title>
  <!-- Favicon-->
  <link
    rel="icon"
    type="image/x-icon"
    href="{% static 'assets/favicon.png' %} "
  />
  <!-- Font Awesome icons (free version)-->
  <script
    src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
    crossorigin="anonymous"
  ></script>
  <!-- Google fonts-->
  <link
    href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700"
    rel="stylesheet"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
    rel="stylesheet"
    type="text/css"
  />
  <!-- Third party plugin CSS-->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
    rel="stylesheet"
  />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
</head>

templates/snippets/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}"
      ><img
        src="{% static 'assets/logo.png' %}"
        alt="logo"
        style="height: 30px"
      />
      Pur Beurre</a
    >
    <button
      id="responsive-button"
      class="navbar-toggler navbar-toggler-right"
      type="button"
      data-toggle="collapse"
      data-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto my-2 my-lg-0">
        <li class="form-inline">
          <form
            class=""
            action="{% url 'substitute:check_query' %}"
            method="post"
            accept-charset="utf-8"
          >
            {% csrf_token %}
            <input
              id="searchForm"
              class="form-control bg-light"
              name="query"
              placeholder="Chercher"
            />
          </form>
        </li>

        {% if request.user.is_authenticated %}

        <li id="account-button" class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'account' %}">
            <i class="far fa-user fa-2x"></i>
          </a>
        </li>
        <li id="fav-button" class="nav-item">
          <a
            class="nav-link js-scroll-trigger"
            href="{% url 'substitute:my_food' %}"
            ><i class="fas fa-carrot fa-2x"></i
          ></a>
        </li>
        <li id="calcul-button" class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'calcul_kcal:home' %}">
            
            <i class="fas fa-calculator fa-2x"></i>

          </a>
        </li>
        <li id="logout-button" class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}">
            <i class="fas fa-sign-out-alt fa-2x"></i>
          </a>
        </li>

        
        {% else %}
        <li id="login-button" class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'login' %}">
            <i class="fas fa-sign-in-alt fa-2x"></i>
          </a>
        </li>
        <li id="register-button" class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'register' %}">
            <i class="fas fa-user-plus fa-2x"></i>
          </a>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>